#!/bin/sh

uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/argon_light
uci commit luci

uci set system.@system[0].hostname=Router
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@watchcat[0].pingperiod=30m
uci commit system

uci set network.lan.ipaddr=192.168.123.1
uci commit network

uci set wireless.@wifi-device[0].disabled=1
uci set wireless.@wifi-device[0].channel=auto
uci set wireless.@wifi-device[0].country=CN
uci set wireless.@wifi-iface[0].ssid=FeiSu_2.4G
uci set wireless.@wifi-iface[0].encryption=psk-mixed
uci set wireless.@wifi-iface[0].key=steam888999!
uci set wireless.@wifi-device[1].disabled=1
uci set wireless.@wifi-device[1].channel=auto
uci set wireless.@wifi-device[1].country=CN
uci set wireless.@wifi-iface[1].ssid=FeiSu_5G
uci set wireless.@wifi-iface[1].encryption=psk-mixed
uci set wireless.@wifi-iface[1].key=steam888999!
uci commit wireless

uci set firewall.@defaults[0].flow_offloading=1
uci set firewall.@defaults[0].flow_offloading_hw=1
uci commit firewall

echo "00 5 * * 1 sleep 5 && touch /etc/banner && reboot" >> /etc/crontabs/root

sed -i 's/root::0:0:99999:7:::/root:$1$kVZRVpWL$tXnxH2uSjd6lGCQuuGC65/:0:0:99999:7:::/g' /etc/shadow

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R8.3.19.0410'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Router'" >> /etc/openwrt_release

sed -i '/Powered by/d' /usr/lib/lua/luci/view/themes/argon_dark/footer.htm
sed -i '/Powered by/d' /usr/lib/lua/luci/view/themes/argon_dark_purple/footer.htm
sed -i '/Powered by/d' /usr/lib/lua/luci/view/themes/argon_light/footer.htm
sed -i '/Powered by/d' /usr/lib/lua/luci/view/themes/argon_light_green/footer.htm

#sed -i '434,449d' /usr/lib/lua/luci/view/admin_status/index.htm
#sed -i '/:Model/d' /usr/lib/lua/luci/view/admin_status/index.htm
#sed -i '/:Architecture/d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '/<%=pcdata(ver.distname)%> <%=pcdata(ver.distversion)%>/d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i 's/<%=pcdata(ver.luciname)%> (<%=pcdata(ver.luciversion)%>)/<%=pcdata(ver.distname)%> <%=pcdata(ver.distversion)%>/g' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '17,30d' /usr/lib/lua/luci/view/admin_system/flashops.htm
sed -i '/backupfiles/d' /usr/lib/lua/luci/view/admin_system/flashops.htm

#sed -i '26,86d' /usr/lib/lua/luci/controller/admin/network.lua
sed -i 's/entry({"admin", "system", "system"}/-- entry({"admin", "system", "system"}/g' /usr/lib/lua/luci/controller/admin/system.lua
sed -i 's/entry({"admin", "system", "admin"}/-- entry({"admin", "system", "admin"}/g' /usr/lib/lua/luci/controller/admin/system.lua
sed -i 's/entry({"admin", "system", "packages"}/-- entry({"admin", "system", "packages"}/g' /usr/lib/lua/luci/controller/admin/system.lua
sed -i 's/entry({"admin", "system", "startup"}/-- entry({"admin", "system", "startup"}/g' /usr/lib/lua/luci/controller/admin/system.lua
sed -i 's/entry({"admin", "system", "crontab"}/-- entry({"admin", "system", "crontab"}/g' /usr/lib/lua/luci/controller/admin/system.lua
sed -i 's/entry({"admin", "system", "leds"}/-- entry({"admin", "system", "leds"}/g' /usr/lib/lua/luci/controller/admin/system.lua
sed -i 's/entry({"admin", "status", "syslog"}/-- entry({"admin", "status", "syslog"}/g' /usr/lib/lua/luci/controller/admin/status.lua
sed -i 's/entry({"admin", "status", "dmesg"}/-- entry({"admin", "status", "dmesg"}/g' /usr/lib/lua/luci/controller/admin/status.lua
sed -i 's/entry({"admin", "status", "processes"}/-- entry({"admin", "status", "processes"}/g' /usr/lib/lua/luci/controller/admin/status.lua
sed -i 's/entry({"admin","services","frp"}/-- entry({"admin","services","frp"}/g' /usr/lib/lua/luci/controller/frp.lua
sed -i 's/entry({"admin","services","smartdns"}/-- entry({"admin","services","smartdns"}/g' /usr/lib/lua/luci/controller/smartdns.lua

sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf

rm -rf /etc/config/passwall_show
rm -rf /tmp/luci-*

exit 0
